const HQ_T = {
  uk: {
    // Nav
    'nav.brand':       'Штаб-квартира',
    'nav.programs':    'Програми',
    'nav.projects':    'Проєкти',
    'nav.team':        'Команда',
    'nav.join':        'Долучитись',
    // Hero
    'hero.eyebrow':    'Глобальна мережа українських лідерів',
    'hero.title':      'Ми будуємо<br><em>майбутнє</em> України<br>разом',
    'hero.sub':        'HQ — платформа, що перетворює розпорошену діаспору на глобальну мережу організацій, лідерів та ідей для стратегічного посилення України у світі та її довгострокового розвитку.',
    'hero.vision_l':   'Візія',
    'hero.vision':     'Українська молодь по світу — це глобальна сила, яка поколіннями підтримує і розвиває успішну Україну.',
    'hero.mission_l':  'Місія',
    'hero.mission':    "Об'єднувати та навчати українську молодь у світі для посилення впливу України та формування надійного зв'язку з домом для майбутнього повернення.",
    'hero.cta1':       'Долучитись до мережі',
    'hero.cta2':       'Дізнатись більше',
    'hero.scroll':     'Гортати',
    // KPI
    'kpi.orgs':        'Організацій у мережі',
    'kpi.countries':   'Країн присутності',
    'kpi.applications':'Заявок на інтернатуру',
    'kpi.programs':    'Флагманські програми',
    // Constellation
    'const.tag':       'Сузір\'я',
    'const.title':     'Мережа присутності в <em>20 країнах</em>',
    'const.sub':       'HQ об\'єднує провідні українські молодіжні організації, університетські клуби та ініціативи по всьому світу в єдину координовану систему.',
    'map.all':         'Всі країни',
    'map.ua.sub':      'HQ — Штаб-квартира · Центральний вузол мережі',
    'country.ua':      'Україна',
    'map.org.ro':      'Асоціація Української Молоді в Румунії',
    'map.org.lt':      'Українська Молодіжна Група в Литві',
    'map.org.nl':      'Фонд Лотус / Станція Коновальця',
    'map.org.ch':      'UASAZ — Українські студенти в Цюриху',
    'map.org.fr':      'Наше студентство у Франції',
    'map.org.gb':      'UA.Youth / Oxford Ukrainian Society / Cambridge Ukrainian Society',
    'map.org.be':      "Українська Молодь Об'єднана в Бельгії",
    'map.org.cz':      'Покоління для України',
    'map.org.pl':      'Європейська Україна / Альянс 24/08 / Molodi',
    'map.org.ge':      'Українські активісти в Сакартвело',
    'map.org.es':      'Асоціація українських студентів в Іспанії',
    'map.org.dk':      'Ukrainsk Ungdom i Danmark',
    'map.org.at':      'ЮНІЯ — Українські студенти в Австрії',
    'map.org.us':      'MIT / Harvard / Brown / Georgetown / AU / GWU',
    'map.org.ca':      'Спілка Українських Студентів у Канаді',
    'map.org.it':      'Українсько-італійська молодіжна організація UaMi',
    // Shift
    'shift.tag':       'The Shift',
    'shift.title':     'Від діаспори<br>до <em>мережі</em>',
    'shift.sub':       'Ми змінюємо підхід до того, як Україна взаємодіє зі своїми людьми за кордоном.',
    'shift.from1':     'Розпорошена діаспора',
    'shift.to1':       'Глобальна мережа',
    'shift.from2':     'Тимчасова мобільність',
    'shift.to2':       'Довгостроковий капітал',
    'shift.from3':     'Втрата людей',
    'shift.to3':       'Нова еліта',
    // Products
    'prod.tag':        'Наші програми',
    'prod.title':      'Чотири напрями роботи',
    'prod.sub':        'Системний підхід від побудови мережі до формування нового покоління управлінців.',
    'prod.suz.name':   'Сузір\'я',
    'prod.suz.desc':   'Глобальна мережа українських організацій та ініціатив, об\'єднаних спільною метою.',
    'prod.int.desc':   'Освітня програма для формування нового покоління управлінців. 150+ заявок / 10 позицій.',
    'prod.emb.name':   'Посольства',
    'prod.emb.desc':   'Стажування в посольствах України — інтеграція молоді в міжнародні процеси.',
    'prod.hrom.name':  'Громади',
    'prod.hrom.desc':  'Дистанційне залучення до громад — механізми участі у розвитку конкретних громад в Україні.',
    'prod.ment.name':  'Менторство',
    'prod.ment.desc':  'Програма менторства для молодих лідерів від досвідчених українських управлінців.',
    'prod.idea.name':  'Ваша ідея',
    'prod.idea.desc':  'Маєте ідею для співпраці? Зв\'яжіться з нами.',
    'prod.more':       'Дізнатись більше →',
    // Mentorship
    'ment.tag':        'Менторство',
    'ment.title':      'Досвід, що<br><em>передається</em>',
    'ment.sub':        'Програма з\'єднує молодих українських лідерів з досвідченими фахівцями у сферах державного управління, дипломатії та бізнесу.',
    'ment.s1t':        'Подача заявки',
    'ment.s1d':        'розкажіть про свої цілі та сферу розвитку',
    'ment.s2t':        'Метч з ментором',
    'ment.s2d':        'підбір на основі напряму та потреб',
    'ment.s3t':        '3 місяці роботи',
    'ment.s3d':        'регулярні сесії, конкретні результати',
    'ment.cta':        'Подати заявку',
    // Approach
    'appr.tag':        'Наш підхід',
    'appr.title':      'Чотири виміри нашої роботи',
    'appr.01tag':      'Об\'єднання',
    'appr.02tag':      'Навчання',
    'appr.03tag':      'Вплив',
    'appr.04tag':      'Якір',
    'appr.01h':        'Будуємо Сузір\'я',
    'appr.02h':        'Розвиваємо майбутніх лідерів',
    'appr.03h':        'Формуємо Політики та глобальне бачення',
    'appr.04h':        'Тримаємо Україну в центрі подій',
    'appr.01t':        'Ми об\'єднуємо українські організації, лідерів і експертів по всьому світу в єдину систему.',
    'appr.01f':        'Flagship: Сузір\'я — глобальна мережа українських ініціатив',
    'appr.02t':        'Ми створюємо освітні та професійні можливості для формування нового покоління управлінців.',
    'appr.02f':        'Flagship: HQ Internship Programme — 150+ заявок / 10 позицій',
    'appr.03t':        'Ми інтегруємо українську молодь у міжнародні процеси, політики та адвокацію.',
    'appr.03f':        'Flagship: Стажування в посольствах України',
    'appr.04t':        'Ми створюємо механізми повернення та дистанційного залучення.',
    'appr.04f':        'Flagship: Дистанційне залучення до громад',
    // Why
    'why.statement':   'Без системної роботи Україна ризикує <em>втратити покоління</em>.<br>З правильною системою — це покоління стає новим <em>державним, дипломатичним та управлінським потенціалом</em>.',
    'why.cta':         'Переглянути проєкти',
    // Partners
    'part.tag':        'Наші партнери',
    'part.title':      'Разом із лідерами сектору',
    // CTA
    'cta.tag':         'Долучайтеся',
    'cta.who1':        'Українська спільнота за кордоном',
    'cta.who2':        'Молодіжні організації',
    'cta.who3':        'Інституції',
    'cta.who4':        'Партнери',
    'cta.btn1':        'Долучитись',
    'cta.btn2':        'Партнерство',
    // Nav
    'nav.charter':     'Хартія',
    // Footer
    'ft.desc':         'Глобальна мережа українських організацій та лідерів.',
    'ft.col1':         'Сторінки',
    'ft.home':         'Головна',
    'ft.programs':     'Програми',
    'ft.projects':     'Проєкти',
    'ft.team':         'Команда',
    'ft.charter':      'Хартія',
    'ft.contact':      'Контакт',
    'ft.col2':         'Програми',
    'ft.col3':         'Соцмережі',
    'ft.built':        'Побудовано для України',
    // Charter page
    'charter.tag':          'Документ',
    'charter.title':        'Хартія<br><em>Української Молоді</em>',
    'charter.sub':          'Засадничий документ, що визначає цінності, зобов\'язання та місію глобальної спільноти українських молодих людей.',
    'charter.why.tag':      'Суть та причина',
    'charter.why.title':    'Навіщо потрібна<br><em>Хартія</em>',
    'charter.why.lead':     'Українська молодь по всьому світу — це не просто діаспора. Це <strong>глобальна сила</strong>, здатна формувати майбутнє країни з будь-якої точки планети. Хартія стала відповіддю на потребу в єдиному фундаменті — спільних цінностях і принципах, що об\'єднують нас попри кордони.',
    'charter.c1.title':     'Єдина ідентичність',
    'charter.c1.text':      'Хартія формулює те, що нас об\'єднує — незалежно від країни проживання, покоління чи напрямку діяльності. Це спільна мова для 30+ організацій у 20 країнах.',
    'charter.c2.title':     'Зобов\'язання перед Україною',
    'charter.c2.text':      'Кожен підписант бере на себе конкретні зобов\'язання — активно сприяти розвитку та посиленню України через свою діяльність за кордоном.',
    'charter.c3.title':     'Основа для партнерств',
    'charter.c3.text':      'Хартія слугує фундаментом для всіх програм та ініціатив HQ. Організації, що підписали документ, стають повноправними членами мережі Сузір\'я.',
    'charter.c4.title':     'Відповідь на виклики часу',
    'charter.c4.text':      'Хартія з\'явилась у відповідь на реальні виклики: фрагментованість спільноти, брак координації та необхідність системного погляду на роль молоді у відбудові країни.',
    'charter.doc.tag':      'Документ',
    'charter.doc.title':    'Ознайомтесь<br>з <em>повним текстом</em>',
    'charter.doc.sub':      'Відкрийте або завантажте офіційний текст Хартії Української Молоді.',
    'charter.pdf.label':    'Офіційний документ',
    'charter.pdf.name':     'Charter of Ukrainian Youth',
    'charter.pdf.open':     'Відкрити PDF →',
    'charter.pdf.download': 'Завантажити',
    'charter.cta.title':    'Готові підписати<br>Хартію?',
    'charter.cta.sub':      'Приєднайтесь до спільноти українських молодих людей, що формують майбутнє разом.',
    'charter.cta.btn':      'Приєднатись',
    // Team page
    'team.tag':        'Команда',
    'team.title':      'Люди, що будують<br><em>мережу майбутнього</em>',
    'team.sub':        'Невелика команда з великою місією. Ми віримо, що правильна інфраструктура може змінити те, як Україна взаємодіє зі своїм потенціалом у світі.',
    'team.section':    'Наша команда',
    'team.who':        'Хто ми',
    'team.d.role':     'Засновниця і директорка',
    'team.d.bio':      'Архітекторка мережі HQ. Координує стратегічний напрям, партнерства та розвиток організації.',
    'team.n.role':     'Засновник і координатор програм',
    'team.n.bio':      'Відповідає за операційну діяльність флагманських програм та фандрейзинг.',
    'team.r.role':     'Засновниця і менеджерка зі стратегічного розвитку',
    'team.r.bio':      'Відповідає за розвиток стратегічних програм.',
    'team.s.role':     'Засновниця і менеджерка програм залучення молоді',
    'team.s.bio':      'Відповідає за програми залучення молоді.',
    'team.l.role':     'Засновниця і менеджерка напрямку молодіжної дипломатії',
    'team.l.bio':      'Координує комунікацію з МЗС.',
    'team.join.tag':   'Долучайтеся',
    'team.join.title': 'Хочете приєднатись<br><em>до команди?</em>',
    'team.join.sub':   'Ми шукаємо людей, що поділяють нашу місію та хочуть реально впливати на майбутнє України.',
    'team.join.btn':   'Написати нам',
    // Products page
    'prod.page.tag':    'Наші програми',
    'prod.page.title':  'Системні рішення для<br><em>нового покоління</em>',
    'prod.page.sub':    "П'ять взаємопов'язаних програм, що формують повний цикл від побудови мережі до виховання нової управлінської еліти.",
    'prod.suz.tagline': "Connect — Глобальна мережа українських організацій",
    'prod.suz.apply':   'Подати заявку',
    'prod.suz.full':    "Сузір'я — це координаційна платформа, що об'єднує 30+ українських молодіжних організацій у 20 країнах. Ми створюємо єдиний простір для обміну досвідом, ресурсами та стратегічного планування спільних дій.",
    'prod.suz.f1':      '30+ організацій у 20 країнах',
    'prod.suz.f2':      'Регулярні координаційні зустрічі',
    'prod.suz.f3':      'Платформа обміну знаннями',
    'prod.suz.f4':      'Спільні проєкти та ініціативи',
    'prod.int.tagline': 'Learn — Освітня програма для лідерів',
    'prod.int.full':    "Тримісячна інтенсивна програма для найкращих молодих українців. 150+ заявок на 10 позицій — конкурентний відбір забезпечує найвищий рівень учасників. Реальні завдання, реальний вплив.",
    'prod.int.f1':      '3-місячна програма з реальними завданнями',
    'prod.int.f2':      'Менторство від досвідчених фахівців',
    'prod.int.f3':      'Доступ до мережі HQ',
    'prod.int.f4':      'Сертифікація та рекомендації',
    'prod.emb.tagline': 'Influence — Дипломатичні стажування',
    'prod.emb.full':    "Партнерство з МЗС України відкриває унікальну можливість пройти стажування безпосередньо в посольствах. Програма готує нове покоління українських дипломатів та державних управлінців.",
    'prod.emb.f1':      'Партнерство з МЗС України',
    'prod.emb.f2':      'Стажування в 10+ посольствах',
    'prod.emb.f3':      'Реальний дипломатичний досвід',
    'prod.emb.f4':      "Підготовка до кар'єри у держсекторі",
    'prod.hrom.tagline':'Anchor — Дистанційне залучення до громад',
    'prod.hrom.full':   "Механізми, що дозволяють українцям за кордоном активно долучатись до розвитку конкретних громад в Україні. Remote engagement — ефективна модель збереження зв'язку з батьківщиною.",
    'prod.hrom.f1':     'Партнерство з 20+ громадами',
    'prod.hrom.f2':     'Дистанційні формати участі',
    'prod.hrom.f3':     'Підтримка проєктів та менторство',
    'prod.hrom.f4':     'Платформа для повернення',
    'prod.ment.tagline':'Mentorship — Індивідуальний розвиток лідерів',
    'prod.ment.full':   "Персоналізований підбір пар ментор–менті на основі цілей та напряму розвитку. Тримісячні цикли з чіткими результатами та доступом до всієї мережі HQ.",
    'prod.ment.f1':     'Індивідуальний підбір ментора',
    'prod.ment.f2':     '3-місячні цикли з чіткими результатами',
    'prod.ment.f3':     'Доступ до мережі HQ',
    'prod.ment.f4':     'Сесії та практичні завдання',
    'prod.cta.tag':     'Долучайтеся',
    'prod.cta.title':   'Готові стати частиною<br><em>глобальної мережі?</em>',
    'prod.cta.apply':   'Подати заявку',
    'prod.cta.learn':   'Дізнатись більше',
    // Projects page
    'proj.tag':         'Проєкти',
    'proj.title':       'Реальні результати<br><em>реальних людей</em>',
    'proj.sub':         'Від глобальних форумів до локальних ініціатив — кожен проєкт HQ є кроком до системних змін в Україні та українській спільноті.',
    'proj.section':     'Що ми реалізували',
    'proj.p1.tag':      'Мережа',
    'proj.p1.name':     'Глобальний Форум Українських Організацій 2026',
    'proj.p1.desc':     'Перша масштабна координаційна зустріч представників 30+ організацій у 20 країнах. Встановлено стандарти взаємодії та спільні пріоритети на 2026 рік.',
    'proj.p2.tag':      'Інтернатура',
    'proj.p2.name':     'HQ Internship — Перший набір',
    'proj.p2.desc':     '150+ заявок, 10 відібраних учасників. Двомісячна програма з реальними завданнями у сфері комунікацій, аналітики та управління проєктами.',
    'proj.p3.tag':      'Дипломатія',
    'proj.p3.name':     'Програма Посольств — Пілот',
    'proj.p3.desc':     'Пропозиція пілотного запуску у партнерстві з МЗС України. Учасники зможуть пройти стажування у посольствах, розроблено модель для масштабування.',
    'proj.p4.tag':      'Громади',
    'proj.p4.name':     'Міст до громад',
    'proj.p4.desc':     'Ми переводимо глобальну молодь у реальний вплив. Через дистанційну участь молодь працює з громадами: залучає ресурси, будує партнерства, розвиває проєкти. Це перехід від "зв\'язку з Україною" → до внеску в Україну.',
    'proj.p5.tag':      'Освіта',
    'proj.p5.name':     'Освіта для лідерства діаспори',
    'proj.p5.desc':     'Серія освітніх сесій та воркшопів для лідерів українських організацій за кордоном. Теми: стратегічне планування, комунікації, фандрейзинг.',
    'proj.p6.tag':      'Партнерства',
    'proj.p6.name':     'Університетські партнерства',
    'proj.p6.desc':     'Налагодження формальних партнерств з університетськими українськими клубами в США, Великій Британії та Канаді. База для HQ Internship та Менторства.',
    'proj.cta.tag':     'Долучайтеся',
    'proj.cta.title':   'Маєте ідею для<br><em>спільного проєкту?</em>',
    'proj.cta.sub':     'Ми відкриті до партнерства, ко-реалізації та нових ідей.',
    'proj.cta.btn1':    "Зв'язатись з нами",
    'proj.cta.btn2':    'Наші програми',
    // Contact page
    'cont.tag':         'Контакт',
    'cont.title':       'Давайте будувати<br><em>разом</em>',
    'cont.sub':         'Незалежно від того, чи ви — організація, студент, ментор чи інституція — у нас є формат співпраці саме для вас.',
    'cont.formats.tag': 'Формати співпраці',
    'cont.formats.title':'Як ми можемо<br>працювати <em>разом</em>',
    'cont.f1.name':     'Приєднатись до мережі',
    'cont.f1.desc':     "Ваша організація в мережі Сузір'я — спільна координація, ресурси та видимість серед 30+ партнерів у 20 країнах.",
    'cont.f2.name':     'Стажування та менторство',
    'cont.f2.desc':     'Подайте заявку на HQ Internship або Менторську програму. Реальний досвід та підтримка досвідчених фахівців.',
    'cont.f3.name':     'Інституційне партнерство',
    'cont.f3.desc':     'Стратегічне партнерство для організацій, університетів та інституцій, що розділяють нашу місію.',
    'cont.form.tag':    "Зв'яжіться з нами",
    'cont.form.title':  'Ми готові<br>до розмови',
    'cont.form.h':      'Надіслати повідомлення',
    'cont.form.name':   "Ім'я",
    'cont.form.name_ph':"Ваше ім'я",
    'cont.form.phone':  'Телефон',
    'cont.form.phone_ph':'+380...',
    'cont.form.topic':  'Тема звернення',
    'cont.form.topic_ph':'Оберіть тему',
    'cont.form.opt1':   'Приєднатись до мережі',
    'cont.form.opt2':   'HQ Internship',
    'cont.form.opt3':   'Менторська програма',
    'cont.form.opt4':   'Посольства',
    'cont.form.opt5':   'Громади',
    'cont.form.opt6':   'Інституційне партнерство',
    'cont.form.opt7':   'Інше',
    'cont.form.msg':    'Повідомлення',
    'cont.form.msg_ph': 'Розкажіть про себе та вашу ідею...',
    'cont.form.submit': 'Надіслати →',
    'cont.social':      'Соціальні мережі',
    'cont.network':     "Мережа Сузір'я",
    'cont.orgs':        'Організацій',
    'cont.countries':   'Країн',
    'cont.toast':       "Ваш запит прийнято — ми зв'яжемось незабаром",
    // Country page
    'cntry.back':       'Назад до мапи',
    'cntry.constellation': "Сузір'я HQ",
    'cntry.partner':    'Організація-партнер',
    'cntry.country_l':  'Країна:',
    'cntry.network_l':  'Мережа:',
    'cntry.network_v':  "Сузір'я HQ — глобальна мережа українських молодіжних організацій",
    'cntry.visit':      'Відвідати сайт організації →',
    'cntry.no_web':     "Сайт організації поки недоступний. Зв'яжіться з нами для деталей.",
    'cntry.notfound_h': 'Країну не знайдено',
    'cntry.notfound_p': 'Перевірте посилання або поверніться на головну.',
    'cntry.to_map':     'На карту',
    // Country chips
    'country.ro': 'Румунія',
    'country.lt': 'Литва',
    'country.nl': 'Нідерланди',
    'country.ch': 'Швейцарія',
    'country.fr': 'Франція',
    'country.gb': 'Велика Британія',
    'country.be': 'Бельгія',
    'country.cz': 'Чехія',
    'country.pl': 'Польща',
    'country.ge': 'Сакартвело',
    'country.es': 'Іспанія',
    'country.dk': 'Данія',
    'country.at': 'Австрія',
    'country.us': 'США',
    'country.ca': 'Канада',
    'country.it': 'Італія',
  },
  en: {
    // Nav
    'nav.brand':       'Headquarters',
    'nav.programs':    'Programs',
    'nav.projects':    'Projects',
    'nav.team':        'Team',
    'nav.join':        'Get involved',
    // Hero
    'hero.eyebrow':    'Global network of Ukrainian leaders',
    'hero.title':      'We are building<br><em>the future</em> of Ukraine<br>together',
    'hero.sub':        'HQ is a platform that transforms the scattered diaspora into a global network of organizations, leaders and ideas for the strategic strengthening of Ukraine in the world and its long-term development.',
    'hero.vision_l':   'Vision',
    'hero.vision':     'Ukrainian youth around the world is a global force that sustains and develops a successful Ukraine across generations.',
    'hero.mission_l':  'Mission',
    'hero.mission':    "To unite and educate Ukrainian youth worldwide to amplify Ukraine's influence and build a lasting connection with home for future return.",
    'hero.cta1':       'Join the network',
    'hero.cta2':       'Learn more',
    'hero.scroll':     'Scroll',
    // KPI
    'kpi.orgs':        'Organizations in network',
    'kpi.countries':   'Countries',
    'kpi.applications':'Internship applications',
    'kpi.programs':    'Flagship programs',
    // Constellation
    'const.tag':       'Constellation',
    'const.title':     'Network presence in <em>20 countries</em>',
    'const.sub':       'HQ unites leading Ukrainian youth organizations, university clubs and initiatives across the world into a single coordinated system.',
    'map.all':         'All countries',
    'map.ua.sub':      'HQ — Headquarters · Central network hub',
    'country.ua':      'Ukraine',
    'map.org.ro':      'Association of Ukrainian Youth in Romania',
    'map.org.lt':      'Ukrainian Youth Group in Lithuania',
    'map.org.nl':      'Lotus Foundation / Konovaets Station',
    'map.org.ch':      'UASAZ — Ukrainian Students in Zurich',
    'map.org.fr':      'Our Students in France',
    'map.org.gb':      'UA.Youth / Oxford Ukrainian Society / Cambridge Ukrainian Society',
    'map.org.be':      'Ukrainian Youth United in Belgium',
    'map.org.cz':      'Generation for Ukraine',
    'map.org.pl':      'European Ukraine / Alliance 24/08 / Molodi',
    'map.org.ge':      'Ukrainian Activists in Georgia',
    'map.org.es':      'Association of Ukrainian Students in Spain',
    'map.org.dk':      'Ukrainsk Ungdom i Danmark',
    'map.org.at':      'UNIA — Ukrainian Students in Austria',
    'map.org.us':      'MIT / Harvard / Brown / Georgetown / AU / GWU',
    'map.org.ca':      'Union of Ukrainian Students in Canada',
    'map.org.it':      'Ukrainian-Italian Youth Organization UaMi',
    // Shift
    'shift.tag':       'The Shift',
    'shift.title':     'From diaspora<br>to <em>network</em>',
    'shift.sub':       'We are changing the approach to how Ukraine engages with its people abroad.',
    'shift.from1':     'Scattered diaspora',
    'shift.to1':       'Global network',
    'shift.from2':     'Temporary mobility',
    'shift.to2':       'Long-term capital',
    'shift.from3':     'Brain drain',
    'shift.to3':       'New elite',
    // Products
    'prod.tag':        'Our programs',
    'prod.title':      'Four areas of work',
    'prod.sub':        'A systemic approach from building the network to shaping the next generation of leaders.',
    'prod.suz.name':   'Constellation',
    'prod.suz.desc':   'A global network of Ukrainian organizations and initiatives united by a common purpose.',
    'prod.int.desc':   'An educational program for developing the next generation of leaders. 150+ applications / 10 positions.',
    'prod.emb.name':   'Embassies',
    'prod.emb.desc':   'Internships at Ukrainian embassies — integrating youth into international processes.',
    'prod.hrom.name':  'Communities',
    'prod.hrom.desc':  'Remote engagement in hromadas — mechanisms for remote involvement in community development.',
    'prod.ment.name':  'Mentorship',
    'prod.ment.desc':  'A mentorship program for young leaders from experienced Ukrainian professionals.',
    'prod.idea.name':  'Your idea',
    'prod.idea.desc':  'Have an idea for collaboration? Get in touch.',
    'prod.more':       'Learn more →',
    // Mentorship
    'ment.tag':        'Mentorship',
    'ment.title':      'Experience that<br><em>gets passed on</em>',
    'ment.sub':        'The program connects young Ukrainian leaders with experienced professionals in public administration, diplomacy and business.',
    'ment.s1t':        'Submit application',
    'ment.s1d':        'tell us about your goals and area of development',
    'ment.s2t':        'Mentor match',
    'ment.s2d':        'matched based on direction and needs',
    'ment.s3t':        '3 months of work',
    'ment.s3d':        'regular sessions, concrete results',
    'ment.cta':        'Apply now',
    // Approach
    'appr.tag':        'Our approach',
    'appr.title':      'Four dimensions of our work',
    'appr.01tag':      'Connect',
    'appr.02tag':      'Learn',
    'appr.03tag':      'Influence',
    'appr.04tag':      'Anchor',
    'appr.01h':        'Building the constellation',
    'appr.02h':        'Developing future leaders',
    'appr.03h':        'Shaping policy and global agenda',
    'appr.04h':        'Keeping Ukraine at the center',
    'appr.01t':        'We unite Ukrainian organizations, leaders and experts across the world into a single system.',
    'appr.01f':        'Flagship: Constellation — global network of Ukrainian initiatives',
    'appr.02t':        'We create educational and professional opportunities to develop the next generation of leaders.',
    'appr.02f':        'Flagship: HQ Internship Programme — 150+ applications / 10 positions',
    'appr.03t':        'We integrate Ukrainian youth into international processes, policies and advocacy.',
    'appr.03f':        'Flagship: Internships at Ukrainian embassies',
    'appr.04t':        'We create mechanisms for return and remote engagement.',
    'appr.04f':        'Flagship: Remote engagement in hromadas',
    // Why
    'why.statement':   'Without systemic work, Ukraine risks <em>losing a generation</em>.<br>With the right system — this generation becomes new <em>governance, diplomatic and management potential</em>.',
    'why.cta':         'View projects',
    // Partners
    'part.tag':        'Our partners',
    'part.title':      'Together with sector leaders',
    // CTA
    'cta.tag':         'Get involved',
    'cta.who1':        'Ukrainian community abroad',
    'cta.who2':        'Youth organizations',
    'cta.who3':        'Institutions',
    'cta.who4':        'Partners',
    'cta.btn1':        'Get involved',
    'cta.btn2':        'Partnership',
    // Nav
    'nav.charter':     'Charter',
    // Footer
    'ft.desc':         'Global network of Ukrainian organizations and leaders.',
    'ft.col1':         'Pages',
    'ft.home':         'Home',
    'ft.programs':     'Programs',
    'ft.projects':     'Projects',
    'ft.team':         'Team',
    'ft.charter':      'Charter',
    'ft.contact':      'Contact',
    'ft.col2':         'Programs',
    'ft.col3':         'Social media',
    'ft.built':        'Built for Ukraine',
    // Charter page
    'charter.tag':          'Document',
    'charter.title':        'Charter of<br><em>Ukrainian Youth</em>',
    'charter.sub':          'A foundational document that defines the values, commitments, and mission of the global community of young Ukrainians.',
    'charter.why.tag':      'Purpose & reason',
    'charter.why.title':    'Why the<br><em>Charter</em> matters',
    'charter.why.lead':     'Ukrainian youth around the world are not just a diaspora. They are a <strong>global force</strong> capable of shaping the country\'s future from anywhere on the planet. The Charter emerged as a response to the need for a common foundation — shared values and principles that unite us across borders.',
    'charter.c1.title':     'Shared identity',
    'charter.c1.text':      'The Charter articulates what unites us — regardless of country of residence, generation, or field of activity. It is a common language for 30+ organizations in 20 countries.',
    'charter.c2.title':     'Commitment to Ukraine',
    'charter.c2.text':      'Each signatory makes concrete commitments — to actively contribute to Ukraine\'s development and strengthening through their work abroad.',
    'charter.c3.title':     'Foundation for partnerships',
    'charter.c3.text':      'The Charter serves as the foundation for all HQ programs and initiatives. Organizations that have signed the document become full members of the Constellation network.',
    'charter.c4.title':     'Response to the challenges of our time',
    'charter.c4.text':      'The Charter emerged in response to real challenges: community fragmentation, lack of coordination, and the need for a systemic view of youth\'s role in rebuilding the country.',
    'charter.doc.tag':      'Document',
    'charter.doc.title':    'Read the<br><em>full text</em>',
    'charter.doc.sub':      'Open or download the official text of the Charter of Ukrainian Youth.',
    'charter.pdf.label':    'Official document',
    'charter.pdf.name':     'Charter of Ukrainian Youth',
    'charter.pdf.open':     'Open PDF →',
    'charter.pdf.download': 'Download',
    'charter.cta.title':    'Ready to sign<br>the Charter?',
    'charter.cta.sub':      'Join the community of young Ukrainians shaping the future together.',
    'charter.cta.btn':      'Get involved',
    // Team page
    'team.tag':        'Team',
    'team.title':      'People building<br><em>the network of the future</em>',
    'team.sub':        'A small team with a big mission. We believe the right infrastructure can transform how Ukraine engages with its potential in the world.',
    'team.section':    'Our team',
    'team.who':        'Who we are',
    'team.d.role':     'Co-founder & Director',
    'team.d.bio':      'Architect of the HQ network. Coordinates strategic direction, partnerships and organizational development.',
    'team.n.role':     'Co-founder & Programs Coordinator',
    'team.n.bio':      'Responsible for operations of flagship programs and fundraising.',
    'team.r.role':     'Co-founder & Strategic Manager',
    'team.r.bio':      'Responsible for the development of strategic programs.',
    'team.s.role':     'Co-founder & Youth Engagement Programs Manager',
    'team.s.bio':      'Responsible for youth engagement programs.',
    'team.l.role':     'Co-founder & Youth Diplomacy Direction Manager',
    'team.l.bio':      'Coordinates communication with the Ministry of Foreign Affairs.',
    'team.join.tag':   'Get involved',
    'team.join.title': 'Want to join<br><em>the team?</em>',
    'team.join.sub':   'We are looking for people who share our mission and want to make a real impact on Ukraine\'s future.',
    'team.join.btn':   'Write to us',
    // Products page
    'prod.page.tag':    'Our programs',
    'prod.page.title':  'Systemic solutions for<br><em>the new generation</em>',
    'prod.page.sub':    'Five interconnected programs forming a complete cycle from building the network to developing the new generation of leaders.',
    'prod.suz.tagline': 'Connect — Global network of Ukrainian organizations',
    'prod.suz.apply':   'Apply',
    'prod.suz.full':    'Constellation is a coordination platform uniting 30+ Ukrainian youth organizations in 20 countries. We create a unified space for sharing experience, resources, and joint strategic planning.',
    'prod.suz.f1':      '30+ organizations in 20 countries',
    'prod.suz.f2':      'Regular coordination meetings',
    'prod.suz.f3':      'Knowledge-sharing platform',
    'prod.suz.f4':      'Joint projects and initiatives',
    'prod.int.tagline': 'Learn — Educational program for leaders',
    'prod.int.full':    'A three-month intensive program for the best young Ukrainians. 150+ applications for 10 positions — competitive selection ensures the highest calibre of participants. Real tasks, real impact.',
    'prod.int.f1':      '3-month program with real tasks',
    'prod.int.f2':      'Mentoring from experienced professionals',
    'prod.int.f3':      'Access to the HQ network',
    'prod.int.f4':      'Certification and recommendations',
    'prod.emb.tagline': 'Influence — Diplomatic internships',
    'prod.emb.full':    'Partnership with the Ukrainian MFA opens a unique opportunity to intern directly at embassies. The program trains a new generation of Ukrainian diplomats and public administrators.',
    'prod.emb.f1':      'Partnership with the Ukrainian MFA',
    'prod.emb.f2':      'Internships at 10+ embassies',
    'prod.emb.f3':      'Real diplomatic experience',
    'prod.emb.f4':      'Preparation for a public sector career',
    'prod.hrom.tagline':'Anchor — Remote community engagement',
    'prod.hrom.full':   'Mechanisms that allow Ukrainians abroad to actively contribute to the development of specific communities in Ukraine. Remote engagement — an effective model for maintaining the bond with the homeland.',
    'prod.hrom.f1':     'Partnership with 20+ communities',
    'prod.hrom.f2':     'Remote participation formats',
    'prod.hrom.f3':     'Project support and mentoring',
    'prod.hrom.f4':     'Platform for return',
    'prod.ment.tagline':'Mentorship — Individual leadership development',
    'prod.ment.full':   'Personalized mentor-mentee matching based on goals and development direction. Three-month cycles with clear outcomes and access to the entire HQ network.',
    'prod.ment.f1':     'Individual mentor matching',
    'prod.ment.f2':     '3-month cycles with clear outcomes',
    'prod.ment.f3':     'Access to the HQ network',
    'prod.ment.f4':     'Sessions and practical assignments',
    'prod.cta.tag':     'Get involved',
    'prod.cta.title':   'Ready to become part of the<br><em>global network?</em>',
    'prod.cta.apply':   'Apply',
    'prod.cta.learn':   'Learn more',
    // Projects page
    'proj.tag':         'Projects',
    'proj.title':       'Real results<br><em>of real people</em>',
    'proj.sub':         'From global forums to local initiatives — every HQ project is a step towards systemic change in Ukraine and the Ukrainian community.',
    'proj.section':     'What we have achieved',
    'proj.p1.tag':      'Network',
    'proj.p1.name':     'Global Forum of Ukrainian Organizations 2026',
    'proj.p1.desc':     'The first large-scale coordination meeting of representatives from 30+ organizations in 20 countries. Interaction standards and joint priorities for 2026 were established.',
    'proj.p2.tag':      'Internship',
    'proj.p2.name':     'HQ Internship — First cohort',
    'proj.p2.desc':     '150+ applications, 10 selected participants. A two-month program with real tasks in communications, analytics, and project management.',
    'proj.p3.tag':      'Diplomacy',
    'proj.p3.name':     'Embassy Program — Pilot',
    'proj.p3.desc':     'A proposal for a pilot launch in partnership with the Ukrainian MFA. Participants will be able to complete embassy internships; a scaling model has been developed.',
    'proj.p4.tag':      'Communities',
    'proj.p4.name':     'Bridge to Communities',
    'proj.p4.desc':     'We translate global youth into real impact. Through remote participation, youth works with communities: mobilising resources, building partnerships, developing projects. A shift from "connection to Ukraine" → to contribution to Ukraine.',
    'proj.p5.tag':      'Education',
    'proj.p5.name':     'Education for diaspora leadership',
    'proj.p5.desc':     'A series of educational sessions and workshops for leaders of Ukrainian organizations abroad. Topics: strategic planning, communications, fundraising.',
    'proj.p6.tag':      'Partnerships',
    'proj.p6.name':     'University partnerships',
    'proj.p6.desc':     'Establishing formal partnerships with Ukrainian university clubs in the USA, UK, and Canada. Foundation for HQ Internship and Mentorship.',
    'proj.cta.tag':     'Get involved',
    'proj.cta.title':   'Have an idea for a<br><em>joint project?</em>',
    'proj.cta.sub':     'We are open to partnerships, co-implementation, and new ideas.',
    'proj.cta.btn1':    'Contact us',
    'proj.cta.btn2':    'Our programs',
    // Contact page
    'cont.tag':         'Contact',
    'cont.title':       "Let's build<br><em>together</em>",
    'cont.sub':         'Whether you are an organization, student, mentor, or institution — we have a collaboration format just for you.',
    'cont.formats.tag': 'Formats of cooperation',
    'cont.formats.title':'How we can<br>work <em>together</em>',
    'cont.f1.name':     'Join the network',
    'cont.f1.desc':     'Your organization in the Constellation network — joint coordination, resources, and visibility among 30+ partners in 20 countries.',
    'cont.f2.name':     'Internship and mentorship',
    'cont.f2.desc':     'Apply for HQ Internship or the Mentorship Program. Real experience and support from experienced professionals.',
    'cont.f3.name':     'Institutional partnership',
    'cont.f3.desc':     'Strategic partnership for organizations, universities, and institutions that share our mission.',
    'cont.form.tag':    'Contact us',
    'cont.form.title':  "We are ready<br>for a conversation",
    'cont.form.h':      'Send a message',
    'cont.form.name':   'Name',
    'cont.form.name_ph':'Your name',
    'cont.form.phone':  'Phone',
    'cont.form.phone_ph':'+1...',
    'cont.form.topic':  'Subject',
    'cont.form.topic_ph':'Select a topic',
    'cont.form.opt1':   'Join the network',
    'cont.form.opt2':   'HQ Internship',
    'cont.form.opt3':   'Mentorship program',
    'cont.form.opt4':   'Embassies',
    'cont.form.opt5':   'Communities',
    'cont.form.opt6':   'Institutional partnership',
    'cont.form.opt7':   'Other',
    'cont.form.msg':    'Message',
    'cont.form.msg_ph': 'Tell us about yourself and your idea...',
    'cont.form.submit': 'Send →',
    'cont.social':      'Social media',
    'cont.network':     'Constellation Network',
    'cont.orgs':        'Organizations',
    'cont.countries':   'Countries',
    'cont.toast':       'Your request has been received — we will be in touch shortly',
    // Country page
    'cntry.back':       'Back to map',
    'cntry.constellation': 'HQ Constellation',
    'cntry.partner':    'Partner organization',
    'cntry.country_l':  'Country:',
    'cntry.network_l':  'Network:',
    'cntry.network_v':  'HQ Constellation — global network of Ukrainian youth organizations',
    'cntry.visit':      'Visit organization website →',
    'cntry.no_web':     'Organization website not yet available. Contact us for details.',
    'cntry.notfound_h': 'Country not found',
    'cntry.notfound_p': 'Check the link or return to the home page.',
    'cntry.to_map':     'To the map',
    // Country chips
    'country.ro': 'Romania',
    'country.lt': 'Lithuania',
    'country.nl': 'Netherlands',
    'country.ch': 'Switzerland',
    'country.fr': 'France',
    'country.gb': 'United Kingdom',
    'country.be': 'Belgium',
    'country.cz': 'Czech Republic',
    'country.pl': 'Poland',
    'country.ge': 'Georgia',
    'country.es': 'Spain',
    'country.dk': 'Denmark',
    'country.at': 'Austria',
    'country.us': 'USA',
    'country.ca': 'Canada',
    'country.it': 'Italy',
  }
};

function applyLang(lang) {
  const t = HQ_T[lang];
  if (!t) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.dataset.i18nPh;
    if (t[key] !== undefined) el.placeholder = t[key];
  });
  document.documentElement.lang = lang === 'uk' ? 'uk' : 'en';
  localStorage.setItem('hq-lang', lang);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.textContent = lang === 'uk' ? 'EN' : 'UA';
    btn.dataset.lang = lang;
  });
}

function initLang() {
  const saved = localStorage.getItem('hq-lang') || 'uk';
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.textContent = saved === 'uk' ? 'EN' : 'UA';
    btn.dataset.lang = saved;
    btn.addEventListener('click', () => {
      const current = btn.dataset.lang || 'uk';
      applyLang(current === 'uk' ? 'en' : 'uk');
    });
  });
  if (saved === 'en') applyLang('en');
}

document.addEventListener('DOMContentLoaded', initLang);
